version: '3.8'
services:
  webapi:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build:
      context: ../backend/api
      dockerfile: Dockerfile
    volumes:
      - ../backend/api:/app
    depends_on:
      - db
    ports:
      - "8181:80"

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  postgres_data:
