name: Docker Compose CI

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
