name: Docker Compose CI

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  compose_and_test:
    runs-on: ubuntu-22.04
    env:
      FULLSTACK_AZURE_COGNITIVE_SERVICES: ${{ secrets.FULLSTACK_AZURE_COGNITIVE_SERVICES }}
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v3
      - run: docker-compose up -d
      - name: Install dotnet for local test execution
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: cd backend/Tests && dotnet test
      - run: docker-compose logs && sleep 5
        if: always()
      - run: docker-compose down && sleep 5
        if: always()
