name: Dotnet test

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      FULLSTACK_AZURE_COGNITIVE_SERVICES: ${{ secrets.FULLSTACK_AZURE_COGNITIVE_SERVICES }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: cd backend/Tests && dotnet test